global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "barrett@aivia.ca"
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: ERROR
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  format: json